############################
## CHANGE THESE
############################

baseURL: "https://chrede88.github.io/qubt"
title: "S3ntinl"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
markup:
  goldmark:
    renderHooks:
      image:
        enableDefault: true
