############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Blog 🇺🇸
  url: /blog/
  weight: 20
- name: Blog 🇪🇸
  url: /bloges/
  weight: 30
- name: About
  url: /about/
  weight: 40